server:
  port: 8080

spring:
  datasource:
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
    url: jdbc:postgresql://localhost:5432/advertisement
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 200
        use_sql_comments: true
  liquibase:
    change-log: classpath:/db/changelog/liquibase.xml